[package]
name = "rustml"
version = "0.1.0"
authors = ["David Freifeld <freifeld.david@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"