[package]
name = "rustml"
version = "0.1.0"
authors = ["David Freifeld <freifeld.david@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cuda_std = "0.1.0"

[build-dependencies]
cuda_builder = "0.1.0"
